apiVersion: v1
kind: Pod
metadata:
  name: lifespan-seven
  namespace: apps
spec:
  containers:
    - args:
        - sleep
        - "3600"
      image: busybox
      name: lifespan-seven
      securityContext:
        runAsNonRoot: false
  restartPolicy: Always