
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: self-signer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "webhook.fullname" . }}
spec:
  secretName: {{ .Values.secretName }}
  dnsNames:
    - "{{ include "webhook.fullname" . }}.{{ .Release.Namespace }}.svc"
  issuerRef:
    name: self-signer