apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "webhook.fullname" . }}
  annotations:
    cert-manager.io/inject-ca-from: "{{ .Release.Namespace }}/{{ include "webhook.fullname" . }}"
webhooks:
  - name: "{{ include "webhook.fullname" . }}.alpacked.io"
    namespaceSelector:
      matchLabels:
        admission-webhook: enabled
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE"]
        resources: ["pods"]
        scope: "*"
    clientConfig:
      service:
        namespace: {{ .Release.Namespace }}
        name: {{ include "webhook.fullname" . }}
        path: /mutate-pods
        port: {{ .Values.env.LISTEN_PORT }}
    admissionReviewVersions: ["v1"]
    sideEffects: None
    timeoutSeconds: 5