---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "webhook.fullname" . }}
  labels:
    {{- include "webhook.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 443
      targetPort: 443
      name: https
  selector:
    {{- include "webhook.selectorLabels" . | nindent 4 }}